world = [1, 2, 3, 4]
titles = [
    'Mystical Room',
    "The Chamber of Eternal Silence",
    "The Hall of Forgotten Sorrows",
    "The Crypt of Despair",
    "The Vault of Eternal Rest",
    "The Halls of the Lost",
    "The Pit of Eternal Darkness",
    "The Labyrinth of Shadows",
    "The Abyss of Regret",
    "The Caverns of Sorrow",
    "The Mausoleum of Lost Souls",
    "The Chamber of Thousand Tombs",
    "The Pit of Eternal Darkness",
    "The Hall of the Serpentine Guardian",
    'The Corridor of the Whispering Shadows',
    "The Room of the Undying Flames",
    "The Maze of the Endless Sands",
    "The Vault of the Crimson Moon",
    "The Garden of the Night-Blooming Flowers",
    "The Abyss of the Soulless",
    "The Shrine of the Nameless God",
    "The Den of the Raging Behemoth",
    "The Sanctum of the Mysterious Magus",
    "The Well of the Cursed Waters",
    "The Bridge of the Final Crossing",
    "The Palace of the Silent Sultana",
    "The Tower of the Watchful Djinn",
    "The Chamber of the Black Elixir",
    "The Tomb of the Fallen Kings",
    "The Gallery of the Grotesque",
    "The Grotto of the Raging Torrent",
    "The Garden of the Poisonous Paradise",
    "The Chasm of the Forsaken",
    "The Hall of the Twisted Mirrors",
    "The Labyrinth of the Endless Night",
    "The Crypt of the Unforgiven",
    "The Shrine of the Ever-Burning Fire",
    "The Catacombs of the Nameless",
    "The Den of the Bloodthirsty Vizier",
    "The Pit of the Endless Torment",
    "The Tower of the Immortal Sorcerer",
    "The Bridge of the Doomed Souls",
    "The Chamber of the Thousand Whispers",
    "The Tomb of the Dark Emir",
    "The Gallery of the Unholy Relics",
    "The Corridor of the Burning Sands",
    "The Sanctuary of the Forgotten",
    "The Grotto of the Eternal Ice",
    "The Labyrinth of the Unyielding Darkness",
    "The Hall of the Crimson Throne",
    "The Vault of the Fading Memories",
    "The Palace"
]

description = ['so vague, you cant even tell what shape does it have', 'cold, dark and smells like toast.',
               "A room shrouded in darkness, reflecting the fears and doubts of those who enter it.",
               "A dimly lit chamber, evocative of the gloom of the human soul.",
               "A chamber of shadows, where the echoes of past sins reverberate through the walls.",
               "A chamber where the light of hope struggles to penetrate the gloom of despair.",
               "A place where dreams are lost, and the nightmares of the mind are given form.",
               "A room of dark magic, where the boundary between life and death is blurred...",
               "A hall of mirrors, where the illusions of the self are shattered and reflected back in twisted forms.",
               "A room where the weight of regret is tangible, and the past can never be truly escaped.",
               "A chamber of echoes, where the whispers of the dead can still be heard.",
               "A place where the only escape from the darkness is to embrace it fully."]

obstacles = ['Sufi', "Sphynx", 'Skeleton', 'Ghost', 'Frog', "Portuguese man o' war", "Sandstorm",
             "Sandworm", "Cursed Tree", "Giant Scorpion", "Maze", "Pit Trap", "Sphinx", "Genie", "Ghoul", "Efreet",
             "Jinn",
             "Djinni", "Ifrit", "Vampire", "Mummy from the Brendan Fraser movie", "Siren", "Harpies", "Minotaur",
             "Cyclops", "Hydra",
             "Basilisk", "Chimera", "Griffin", "Dragon", "Demon", "Zombie", "Wraith", "Ghost", "Poltergeist","Shadow",
             'Dark Sorcerer',
             'Jinn of the Lamp', 'Cursed Mummy', 'Sand Golem', 'Fire-breathing Dragon', 'Winged Demon',
             'Vicious Scorpion',
             'Shadow Assassin', 'Black Knight', 'Ancient Sphinx', 'Haunted Djinn Bottle', 'Ghoul Swarm',
             'Demonic Possession', 'Whirling Dervish',
             'Sandstorm Elemental', 'Bone Dragon', 'Blind Seer', 'Scarab Swarm', 'Nightmare Steed', 'Deathly Scimitar',
             'Giant Spider',
             'Poisonous Cobra', 'Immortal Ifrit', 'Living Statue', 'Plague-ridden Rats', 'Skeletal Warrior',
             'Soul Reaper',
             'Sword-wielding Dervish', 'Twisted Marid', 'Wailing Banshee', 'Bloodthirsty Ghoul', 'Armored Scorpion',
             'Burning Phoenix', 'Death Knight',
             'Demonic Incarnation', 'Ethereal Jinni', 'Enslaved Ifrit', 'Frost Giant', 'Mystical Mirror',
             'Necrotic Zombie',
             'Rampaging Minotaur', 'Screaming Harpy', 'Skeletal Lich', 'Swarm of Scarabs', 'Terror Drake',
             'Vengeful Ghost']

doors = ['a', 'b', 'c', 'd']
game_level = [1, 2, 3, 4]
door_open_strings = ['The door opens!', "The door is capable of opening!",
                     "The door has the ability to be opened!",
                     "This door is designed to open!",
                     "The door can be opened!",
                     "The door is not locked and can be opened!",
                     "This door is not stuck and can be opened!",
                     "The door is not jammed and can be opened!",
                     "This door is unlocked and can be opened!",
                     "The door is functional and can be opened!",
                     "This door is operational and can be opened!"
                     ]
door_closed_strings = ['This door would not budge', 'This one needs a key probably',
                       'Wait,this is the wall painted as a door',
                       "The door stands as a barrier, a threshold between what is known and what is not. You cannot enter.",
                       "Beyond the door lies the unknown, the unseen, the undiscovered. No way to open it.",
                       "The door stands as a symbol of the secrets that lie hidden within. Try another one.",
                       "The door is a reminder that sometimes the greatest power lies in not knowing what lies ahead. Go ahead, try another one.",
                       "The door represents the choice between safety and the unknown, between the comfort of the familiar and the danger of the new. No luck opening it.",
                       "The door stands as a testament to the fragility of human curiosity, and the fear that lies at its heart. You sense a thin veil,yet cannot enter.",
                       "The door holds the promise of both revelation and devastation, depending on which side one stands. You do not have to make that choice now though.",
                       "The door is a reminder that the line between safety and peril can be razor-thin. No way in right now.",
                       "The door is a symbol of the fear that comes with the unknown, and the courage required to face it. Try another one.",
                       "The door is a reflection of the human desire to explore, tempered by the knowledge that some things are best left undiscovered. Yet, you need to get out, try another one."]
screens_id = []

# create id, create description (add skeleton text, append words according to other items, description create end
# of the code
# , create choices 1-4, later in the game MAYBE 1-6 (cube), add obstacle from obstacle list
# acle dictionary, dictionary_name[key] = value instead of append
# according to the number of doors
